"""Constants for HA Dreame."""

ATTR_COMPLETED_ITEMS = "completed_items"
ATTR_PENDING_ITEMS = "pending_items"
ATTR_RUNNING_ITEMS = "running_items"
ATTR_TOTAL_ITEMS = "total_items"
CONF_ALLOW_ROBOT_COMMANDS = "allow_robot_commands"
CONF_CONFIG_ENTRY_ID = "config_entry_id"
CONF_ROOM_ID = "room_id"
CONF_ROOM_NAME = "room_name"
CONF_VACUUM_ENTITY_ID = "vacuum_entity_id"
DREAME_VACUUM_DOMAIN = "dreame_vacuum"
DOMAIN = "ha_dreame"
SENSOR_QUEUE_STATUS = "queue_status"
SERVICE_ADD_QUEUE_ROOM = "add_queue_room"
SERVICE_GET_RUNTIME_STATUS = "get_runtime_status"
TITLE = "HA Dreame"
VACUUM_DOMAIN = "vacuum"
