"""Constants for HA Dreame."""

CONF_ALLOW_ROBOT_COMMANDS = "allow_robot_commands"
CONF_CONFIG_ENTRY_ID = "config_entry_id"
CONF_VACUUM_ENTITY_ID = "vacuum_entity_id"
DREAME_VACUUM_DOMAIN = "dreame_vacuum"
DOMAIN = "ha_dreame"
SERVICE_GET_RUNTIME_STATUS = "get_runtime_status"
TITLE = "HA Dreame"
VACUUM_DOMAIN = "vacuum"
